theophilData = [
  {
    file_name: "Theophil_001",
    scientific_name: "Jasminum",
    german: ["Jasmin"],
    english: ["Jasmine"],
    wiki_de: "https://de.wikipedia.org/wiki/Jasminum",
    wiki_en: "https://en.wikipedia.org/wiki/Jasmine",
  },
  {
    file_name: "Theophil_002",
    scientific_name: "Vinca",
    german: ["Immergrün"],
    english: ["periwinkle"],
    wiki_de: "https://de.wikipedia.org/wiki/Immergr%C3%BCn",
    wiki_en: "https://en.wikipedia.org/wiki/Vinca",
  },
  {
    file_name: "Theophil_004",
    scientific_name: "Melissa",
    german: ["Melissen"],
    english: ["lemon balm", "balm"],
    wiki_de: "https://de.wikipedia.org/wiki/Melissen",
    wiki_en: "https://en.wikipedia.org/wiki/Melissa_(plant)",
  },
  {
    file_name: "Theophil_005",
    scientific_name: "Fragaria",
    german: ["Erdbeeren", "Erdbeer"],
    english: ["strawberry"],
    wiki_de: "https://de.wikipedia.org/wiki/Erdbeeren",
    wiki_en: "https://en.wikipedia.org/wiki/Fragaria",
  },
  {
    file_name: "Theophil_006",
    scientific_name: "Vicia faba",
    german: [
      "Ackerbohne",
      "Puffbohne",
      "Feldbohne",
      "Saubohne",
      "Schweinsbohne",
      "Pferdebohne",
      "Fababohne",
      "Faberbohne",
      "Favabohne",
      "Viehbohne",
      "Dicke Bohne",
    ],
    english: [
      "broad bean",
      "fava bean",
      "faba bean",
      "field bean",
      "tic bean",
      "tick bean",
      "Horse bean",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Ackerbohne",
    wiki_en: "https://en.wikipedia.org/wiki/Vicia_faba",
  },
  {
    file_name: "Theophil_007",
    scientific_name: "Stellaria alsine",
    german: ["Bach-Sternmiere", "Quell-Sternmiere"],
    english: ["bog stitchwort"],
    wiki_de: "https://de.wikipedia.org/wiki/Bach-Sternmiere",
    wiki_en: "https://en.wikipedia.org/wiki/Stellaria_alsine",
  },
  {
    file_name: "Theophil_009",
    scientific_name: "Trifolium",
    german: ["Klee"],
    english: ["Clover", "trefoil"],
    wiki_de: "https://de.wikipedia.org/wiki/Klee",
    wiki_en: "https://en.wikipedia.org/wiki/Clover",
  },
  {
    file_name: "Theophil_012",
    scientific_name: "Trifolium",
    german: ["Klee"],
    english: ["Clover", "trefoil"],
    wiki_de: "https://de.wikipedia.org/wiki/Klee",
    wiki_en: "https://en.wikipedia.org/wiki/Clover",
  },
  {
    file_name: "Theophil_010",
    scientific_name: "Oxalis acetosella",
    german: ["Waldsauerklee"],
    english: ["wood sorrel", "common wood sorrel"],
    wiki_de: "https://de.wikipedia.org/wiki/Waldsauerklee",
    wiki_en: "https://en.wikipedia.org/wiki/Oxalis_acetosella",
  },
  {
    file_name: "Theophil_011",
    scientific_name: "Phaseolus",
    german: ["Bohnen"],
    english: ["bean", "wild bean"],
    wiki_de: "https://de.wikipedia.org/wiki/Phaseolus",
    wiki_en: "https://en.wikipedia.org/wiki/Phaseolus",
  },
  {
    file_name: "Theophil_013",
    scientific_name: "Ranunculus",
    german: ["Hahnenfuß", "Ranunkel"],
    english: ["buttercups", "spearworts", "water crowfoots"],
    wiki_de: "https://de.wikipedia.org/wiki/Hahnenfu%C3%9F",
    wiki_en: "https://en.wikipedia.org/wiki/Ranunculus",
  },
  {
    file_name: "Theophil_014",
    scientific_name: "Aquilegia",
    german: ["Akeleien"],
    english: ["granny's bonnet", "columbine"],
    wiki_de: "https://de.wikipedia.org/wiki/Akeleien",
    wiki_en: "https://en.wikipedia.org/wiki/Aquilegia",
  },
  {
    file_name: "Theophil_015",
    scientific_name: "Convolvulus",
    german: ["Winden"],
    english: ["bindweed", "morning glory"],
    wiki_de: "https://de.wikipedia.org/wiki/Winden_(Gattung)",
    wiki_en: "https://en.wikipedia.org/wiki/Convolvulus",
  },
  {
    file_name: "Theophil_017",
    scientific_name: "Cyclamen",
    german: ["Zyklamen", "Alpenveilchen"],
    english: ["cyclamen", "sowbread", "swinebread"],
    wiki_de: "https://de.wikipedia.org/wiki/Alpenveilchen",
    wiki_en: "https://en.wikipedia.org/wiki/Cyclamen",
  },
  {
    file_name: "Theophil_018",
    scientific_name: "Gynostemma pentaphyllum",
    german: ["Jiaogulan"],
    english: ["jiaogulan"],
    wiki_de: "https://de.wikipedia.org/wiki/Gynostemma_pentaphyllum",
    wiki_en: "https://en.wikipedia.org/wiki/Gynostemma_pentaphyllum",
  },
  {
    file_name: "Theophil_019",
    scientific_name: "Hedera helix",
    german: [
      " Efeu",
      "Epheu",
      "Baumwinde",
      "Gemeine Efeu",
      "Gewöhnlicher Efeu",
    ],
    english: [" ivy", "common ivy", "English ivy", "European ivy"],
    wiki_de: "https://de.wikipedia.org/wiki/Gemeiner_Efeu",
    wiki_en: "https://en.wikipedia.org/wiki/Hedera_helix",
  },
  {
    file_name: "Theophil_020",
    scientific_name: "Malva",
    german: ["Malven"],
    english: ["mallow"],
    wiki_de: "https://de.wikipedia.org/wiki/Malven",
    wiki_en: "https://en.wikipedia.org/wiki/Malva",
  },
  {
    file_name: "Theophil_021",
    scientific_name: "Malva",
    german: ["Malven"],
    english: ["mallow"],
    wiki_de: "https://de.wikipedia.org/wiki/Malven",
    wiki_en: "https://en.wikipedia.org/wiki/Malva",
  },
  {
    file_name: "Theophil_022",
    scientific_name: "Asarum",
    german: ["Haselwurzen"],
    english: ["wild ginger"],
    wiki_de: "https://de.wikipedia.org/wiki/Haselwurzen",
    wiki_en: "https://en.wikipedia.org/wiki/Asarum",
  },
  {
    file_name: "Theophil_023",
    scientific_name: "Alchemilla",
    german: ["Frauenmantel", "Silbermantel"],
    english: [" lady's mantle"],
    wiki_de: "https://de.wikipedia.org/wiki/Frauenmantel",
    wiki_en: "https://en.wikipedia.org/wiki/Alchemilla",
  },
  {
    file_name: "Theophil_024",
    scientific_name: "Geranium",
    german: ["Storchschnäbel", "Geranien"],
    english: ["geraniums", "cranesbills"],
    wiki_de: "https://de.wikipedia.org/wiki/Storchschn%C3%A4bel",
    wiki_en: "https://en.wikipedia.org/wiki/Geranium",
  },
  {
    file_name: "Theophil_026",
    scientific_name: "Aristolochia",
    german: ["Pfeifenwinden", "Osterluzei"],
    english: ["birthwort", "pipevine", "Dutchman's pipe"],
    wiki_de: "https://de.wikipedia.org/wiki/Pfeifenblumen",
    wiki_en: "https://en.wikipedia.org/wiki/Aristolochia",
  },
  {
    file_name: "Theophil_026",
    scientific_name: "Viola tricolor",
    german: [
      "Wilde Stiefmütterchen",
      "Ackerveilchen",
      "Muttergottesschuh",
      "Mädchenaugen",
      "Schöngesicht",
      "Liebesgesichtli",
      "Christusauge",
      "Stiefmütterchen",
    ],
    english: ["wild pansy", "heartsease", "heart's ease", "heart's delight"],
    wiki_de: "https://de.wikipedia.org/wiki/Wildes_Stiefm%C3%BCtterchen",
    wiki_en: "https://en.wikipedia.org/wiki/Viola_tricolor",
  },
  {
    file_name: "Theophil_027",
    scientific_name: "Salvia",
    german: ["Salbei"],
    english: ["sage", "rosemary"],
    wiki_de: "https://de.wikipedia.org/wiki/Salbei",
    wiki_en: "https://en.wikipedia.org/wiki/Salvia",
  },
  {
    file_name: "Theophil_028",
    scientific_name: "Myrrhis odorata",
    german: ["Süßdolde", "Myrrhenkerbel"],
    english: [
      "cicely",
      "sweet cicely",
      "myrrh",
      "garden myrrh",
      "sweet chervil",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/S%C3%BC%C3%9Fdolde",
    wiki_en: "https://en.wikipedia.org/wiki/Cicely",
  },
  {
    file_name: "Theophil_029",
    scientific_name: "Salvia sclarea",
    german: [
      "Muskatellersalbei",
      "Muskat-Salbei",
      "Römischer Salbei",
      "Scharlei",
      "Scharlauch",
    ],
    english: ["clary", "clary sage"],
    wiki_de: "https://de.wikipedia.org/wiki/Muskatellersalbei",
    wiki_en: "https://en.wikipedia.org/wiki/Salvia_sclarea",
  },
  {
    file_name: "Theophil_030",
    scientific_name: "Levisticum officinale",
    german: ["Liebstöckel", "Maggikraut", "Lavas", "Luststock", "Nussstock"],
    english: ["Lovage"],
    wiki_de: "https://de.wikipedia.org/wiki/Liebst%C3%B6ckel",
    wiki_en: "https://en.wikipedia.org/wiki/Lovage",
  },
  {
    file_name: "Theophil_032",
    scientific_name: "Artemisia",
    german: ["Beifuß", "Wermut", "Stabwurz", "Edelraute"],
    english: ["mugwort", "wormwood", "sagebrush"],
    wiki_de: "https://de.wikipedia.org/wiki/Artemisia_(Gattung)",
    wiki_en: "https://en.wikipedia.org/wiki/Artemisia_(plant)",
  },
  {
    file_name: "Theophil_033",
    scientific_name: "Tanacetum",
    german: ["Wucherblumen"],
    english: ["tansies"],
    wiki_de: "https://de.wikipedia.org/wiki/Wucherblumen",
    wiki_en: "https://en.wikipedia.org/wiki/Tanacetum",
  },
  {
    file_name: "Theophil_034",
    scientific_name: "Apium graveolens",
    german: ["Echte Sellerie", "Sellerie", "Eppich", "Zeller"],
    english: ["celery"],
    wiki_de: "https://de.wikipedia.org/wiki/Echter_Sellerie",
    wiki_en: "https://en.wikipedia.org/wiki/Celery",
  },
  {
    file_name: "Theophil_035",
    scientific_name: "Petroselinum",
    german: ["Petersilie", "Petersil"],
    english: ["parsley"],
    wiki_de: "https://de.wikipedia.org/wiki/Petroselinum",
    wiki_en: "https://en.wikipedia.org/wiki/Petroselinum",
  },
  {
    file_name: "Theophil_036",
    scientific_name: "Pastinaca sativa",
    german: ["Pastinak", "Pastinake"],
    english: ["parsnip"],
    wiki_de: "https://de.wikipedia.org/wiki/Pastinak",
    wiki_en: "https://en.wikipedia.org/wiki/Parsnip",
  },
  {
    file_name: "Theophil_037",
    scientific_name: "Solanum lycopersicum",
    german: ["Tomate"],
    english: ["tomato"],
    wiki_de: "https://de.wikipedia.org/wiki/Tomate",
    wiki_en: "https://en.wikipedia.org/wiki/Tomato",
  },
  {
    file_name: "Theophil_038",
    scientific_name: "Aegopodium podagraria",
    german: ["Giersch", "Gewöhnlicher Giersch"],
    english: [
      "ground elder",
      "herb gerard",
      "bishop's weed",
      "goutweed",
      "gout wort",
      "English masterwort",
      "wild masterwort",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Giersch",
    wiki_en: "https://en.wikipedia.org/wiki/Aegopodium_podagraria",
  },
  {
    file_name: "Theophil_039",
    scientific_name: "Angelica",
    german: ["Engelwurzen"],
    english: ["angelica"],
    wiki_de: "https://de.wikipedia.org/wiki/Engelwurzen",
    wiki_en: "https://en.wikipedia.org/wiki/Angelica",
  },
  {
    file_name: "Theophil_040",
    scientific_name: "Peucedanum ostruthium",
    german: ["Meisterwurz", "Kaiserwurz", "Ostruz"],
    english: ["masterwort"],
    wiki_de: "https://de.wikipedia.org/wiki/Meisterwurz",
    wiki_en: "https://en.wikipedia.org/wiki/Peucedanum_ostruthium",
  },
  {
    file_name: "Theophil_042",
    scientific_name: "Ribes",
    german: [
      "Johannisbeeren",
      "Ribisl",
      "Träuble",
      "Meertrübeli",
      "Trübeli",
      "Ribiseli",
    ],
    english: ["currants", "gooseberries"],
    wiki_de: "https://de.wikipedia.org/wiki/Johannisbeeren",
    wiki_en: "https://en.wikipedia.org/wiki/Ribes",
  },
  {
    file_name: "Theophil_043",
    scientific_name: "Crataegus",
    german: ["Weißdorne"],
    english: [
      "hawthorn",
      "quickthorn",
      "thornapple",
      "May-tree",
      "whitethorn",
      "hawberry",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Wei%C3%9Fdorne",
    wiki_en: "https://en.wikipedia.org/wiki/Crataegus",
  },
  {
    file_name: "Theophil_044",
    scientific_name: "Cannabis",
    german: ["Hanf"],
    english: ["hemp"],
    wiki_de: "https://de.wikipedia.org/wiki/Hanf",
    wiki_en: "https://en.wikipedia.org/wiki/Cannabis",
  },
  {
    file_name: "Theophil_045",
    scientific_name: "Thalictrum",
    german: ["Wiesenrauten"],
    english: ["Meadow-rue"],
    wiki_de: "https://de.wikipedia.org/wiki/Wiesenrauten",
    wiki_en: "https://en.wikipedia.org/wiki/Thalictrum",
  },
  {
    file_name: "Theophil_046",
    scientific_name: "Ribes uva-crispa",
    german: ["Stachelbeere"],
    english: ["gooseberry", "European gooseberry"],
    wiki_de: "https://en.wikipedia.org/wiki/Ribes_uva-crispa",
    wiki_en: "https://de.wikipedia.org/wiki/Stachelbeere",
  },
  {
    file_name: "Theophil_047",
    scientific_name: "Matricaria",
    german: ["Kamillien"],
    english: ["chamomile"],
    wiki_de: "https://de.wikipedia.org/wiki/Kamillen",
    wiki_en: "https://en.wikipedia.org/wiki/Matricaria",
  },
  {
    file_name: "Theophil_118",
    scientific_name: "Matricaria chamomilla",
    german: ["Echte Kamille", "Kamille"],
    english: ["chamomile", "camomile", "scented mayweed"],
    wiki_de: "https://de.wikipedia.org/wiki/Echte_Kamille",
    wiki_en: "https://en.wikipedia.org/wiki/Matricaria_chamomilla",
  },
  {
    file_name: "Theophil_048",
    scientific_name: "Sanguisorba minor",
    german: ["Kleiner Wiesenknopf", "Pimpinelle", "Pimpernell"],
    english: ["salad burnet", "garden burnet", "small burnet", "burnet"],
    wiki_de: "https://de.wikipedia.org/wiki/Kleiner_Wiesenknopf",
    wiki_en: "https://en.wikipedia.org/wiki/Sanguisorba_minor",
  },
  {
    file_name: "Theophil_049",
    scientific_name: "Polygonatum",
    german: ["Weißwurzen", "Salomonssiegel", "Gelenkwurzen"],
    english: ["King Solomon's-seal", "Solomon's seal"],
    wiki_de: "https://de.wikipedia.org/wiki/Wei%C3%9Fwurzen",
    wiki_en: "https://en.wikipedia.org/wiki/Polygonatum",
  },
  {
    file_name: "Theophil_052",
    scientific_name: "Urtica",
    german: ["Brennnesseln"],
    english: ["nettles", "stinging nettles"],
    wiki_de: "https://de.wikipedia.org/wiki/Brennnesseln",
    wiki_en: "https://en.wikipedia.org/wiki/Urtica",
  },
  {
    file_name: "Theophil_053",
    scientific_name: "Lunaria",
    german: [
      "Silberblatt",
      "Silbertaler",
      "Silberling",
      "Judaspfennig",
      "Mondviole",
    ],
    english: ["honesty"],
    wiki_de: "https://de.wikipedia.org/wiki/Silberbl%C3%A4tter",
    wiki_en: "https://en.wikipedia.org/wiki/Lunaria",
  },
  {
    file_name: "Theophil_055",
    scientific_name: "Arctium lappa",
    german: ["Große Klette"],
    english: [
      "greater burdock",
      "gobō",
      "edible burdock",
      "lappa",
      "beggar's buttons",
      "thorny burr",
      "happy major",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Gro%C3%9Fe_Klette",
    wiki_en: "https://en.wikipedia.org/wiki/Arctium_lappa",
  },
  {
    file_name: "Theophil_056",
    scientific_name: "Leonurus cardiaca",
    german: [
      "Echtes Herzgespann",
      "Herzgespann",
      "Löwenschwanz",
      "Herzspannkraut",
    ],
    english: ["motherwort", "throw-wort", "lion's ear", "lion's tail"],
    wiki_de: "https://de.wikipedia.org/wiki/Echtes_Herzgespann",
    wiki_en: "https://en.wikipedia.org/wiki/Leonurus_cardiaca",
  },
  {
    file_name: "Theophil_057",
    scientific_name: "Sonchus oleraceus",
    german: [
      "Gemüse-Gänsedistel",
      "Kohl-Gänsedistel",
      "Gewöhnliche Gänsedistel",
    ],
    english: [
      "common sowthistle",
      "sow thistle",
      "smooth sow thistle",
      "annual sow thistle",
      "hare's colwort",
      "hare's thistle",
      "milky tassel",
      "milk thistle",
      "soft thistle",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Gem%C3%BCse-G%C3%A4nsedistel",
    wiki_en: "https://en.wikipedia.org/wiki/Sonchus_oleraceus",
  },
  {
    file_name: "Theophil_119",
    scientific_name: "Sonchus oleraceus",
    german: [
      "Gemüse-Gänsedistel",
      "Kohl-Gänsedistel",
      "Gewöhnliche Gänsedistel",
    ],
    english: [
      "common sowthistle",
      "sow thistle",
      "smooth sow thistle",
      "annual sow thistle",
      "hare's colwort",
      "hare's thistle",
      "milky tassel",
      "milk thistle",
      "soft thistle",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Gem%C3%BCse-G%C3%A4nsedistel",
    wiki_en: "https://en.wikipedia.org/wiki/Sonchus_oleraceus",
  },
  {
    file_name: "Theophil_058",
    scientific_name: "Petasites",
    german: ["Pestwurzen"],
    english: ["butterburs", "coltsfoots"],
    wiki_de: "https://de.wikipedia.org/wiki/Pestwurzen",
    wiki_en: "https://en.wikipedia.org/wiki/Petasites",
  },
  {
    file_name: "Theophil_059",
    scientific_name: "Rumex hydrolapathum",
    german: ["Fluss-Ampfer", "Teich-Ampfer", "Riesen-Ampfer"],
    english: ["great water dock", "water dock", "giant water dock"],
    wiki_de: "https://de.wikipedia.org/wiki/Fluss-Ampfer",
    wiki_en: "https://en.wikipedia.org/wiki/Rumex_hydrolapathum",
  },
  {
    file_name: "Theophil_061",
    scientific_name: "Paeonia officinalis",
    german: [
      "Gemeine Pfingstrose",
      "Echte Pfingstrose",
      "Bauern-Pfingstrose",
      "Garten-Pfingstrose",
      "Pfingstrose",
    ],
    english: ["common peony", "garden peony", "peony"],
    wiki_de: "https://de.wikipedia.org/wiki/Gemeine_Pfingstrose",
    wiki_en: "https://en.wikipedia.org/wiki/Paeonia_officinalis",
  },
  {
    file_name: "Theophil_062",
    scientific_name: "Paeonia mascula",
    german: [
      "Großblättrige Pfingstrose",
      "Korallen-Pfingstrose",
      "Pfingstrose",
    ],
    english: ["Peony"],
    wiki_de: "https://en.wikipedia.org/wiki/Paeonia_mascula",
    wiki_en: "https://en.wikipedia.org/wiki/Paeonia_mascula",
  },
  {
    file_name: "Theophil_063",
    scientific_name: "Solanum dulcamara",
    german: [
      "Bittersüßer Nachtschatten",
      "Alpranke",
      "Bittersüß",
      "Hirschkraut",
      "Heischkraut",
      "Mäuseholz",
      "Saurebe",
      "Seidelbeere",
      "wilde Stickwurz",
      "Wasserranke",
    ],
    english: [
      "bittersweet",
      "bittersweet nightshade",
      "bitter nightshade",
      "blue bindweed",
      "Amara Dulcis",
      "fellenwort",
      "felonwood",
      "poisonberry",
      "poisonflower",
      "scarlet berry",
      "snakeberry",
      "trailing bittersweet",
      "trailing nightshade",
      "violet bloom",
      "woody nightshade",
    ],
    wiki_de:
      "https://de.wikipedia.org/wiki/Bitters%C3%BC%C3%9Fer_Nachtschatten",
    wiki_en: "https://en.wikipedia.org/wiki/Solanum_dulcamara",
  },
  {
    file_name: "Theophil_064",
    scientific_name: "Sambucus",
    german: ["Holunder"],
    english: ["elder", "elderberry"],
    wiki_de: "https://de.wikipedia.org/wiki/Holunder",
    wiki_en: "https://en.wikipedia.org/wiki/Sambucus",
  },
  {
    file_name: "Theophil_065",
    scientific_name: "Sorbus aucuparia",
    german: [
      "Vogelbeere",
      "Eberesche",
      "Vogelbeerbaum",
      "Drosselbeere",
      "Quitsche",
      "Krametsbeere",
    ],
    english: ["rowan", "mountain-ash"],
    wiki_de: "https://de.wikipedia.org/wiki/Vogelbeere",
    wiki_en: "https://en.wikipedia.org/wiki/Sorbus_aucuparia",
  },
  {
    file_name: "Theophil_066",
    scientific_name: "Dictamnus",
    german: ["Dictamnus"],
    english: ["burning bush", "dittany", "gas plant", "fraxinella"],
    wiki_de: "https://en.wikipedia.org/wiki/Dictamnus",
    wiki_en: "https://en.wikipedia.org/wiki/Dictamnus",
  },
  {
    file_name: "Theophil_067",
    scientific_name: "Ruta",
    german: ["Rauten"],
    english: ["rue"],
    wiki_de: "https://de.wikipedia.org/wiki/Rauten",
    wiki_en: "https://en.wikipedia.org/wiki/Ruta",
  },
  {
    file_name: "Theophil_069",
    scientific_name: "Juglans regia",
    german: ["Echte Walnuss", "Walnuss", "Nussbaum", "Walnussbaum"],
    english: ["walnut"],
    wiki_de: "https://de.wikipedia.org/wiki/Echte_Walnuss",
    wiki_en: "https://en.wikipedia.org/wiki/Juglans_regia",
  },
  {
    file_name: "Theophil_071",
    scientific_name: "Chelidonium majus",
    german: ["Schöllkraut", ""],
    english: ["greater celandine"],
    wiki_de: "https://de.wikipedia.org/wiki/Sch%C3%B6llkraut",
    wiki_en: "https://en.wikipedia.org/wiki/Chelidonium_majus",
  },
  {
    file_name: "Theophil_073",
    scientific_name: "Taraxacum",
    german: ["Löwenzahn"],
    english: ["dandelions"],
    wiki_de: "https://de.wikipedia.org/wiki/L%C3%B6wenzahn_(Taraxacum)",
    wiki_en: "https://en.wikipedia.org/wiki/Taraxacum",
  },
  {
    file_name: "Theophil_075",
    scientific_name: "Ricinus communis",
    german: ["Wunderbaum", "Rizinus"],
    english: ["castor bean", "castor oil plant"],
    wiki_de: "https://de.wikipedia.org/wiki/Wunderbaum",
    wiki_en: "https://en.wikipedia.org/wiki/Ricinus",
  },
  {
    file_name: "Theophil_076",
    scientific_name: "Brassica rapa",
    german: ["Rübsen"],
    english: [
      "turnip",
      "napa cabbage",
      "bomdong",
      "bok choy",
      "rapini",
      "turnip rape",
      "field mustard",
      "bird rape",
      "keblock",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/R%C3%BCbsen_(Pflanze)",
    wiki_en: "https://en.wikipedia.org/wiki/Brassica_rapa",
  },
  {
    file_name: "Theophil_078",
    scientific_name: "Beta",
    german: ["Rüben"],
    english: ["beet"],
    wiki_de: "https://de.wikipedia.org/wiki/R%C3%BCben",
    wiki_en: "https://en.wikipedia.org/wiki/Beta_vulgaris",
  },
  {
    file_name: "Theophil_079",
    scientific_name: "Plantago",
    german: ["Wegeriche"],
    english: ["plantains", "fleaworts"],
    wiki_de: "https://de.wikipedia.org/wiki/Wegeriche",
    wiki_en: "https://en.wikipedia.org/wiki/Plantago",
  },
  {
    file_name: "Theophil_080",
    scientific_name: "Syringa vulgaris",
    german: ["Gemeiner Flieder", "Flieder", "Gewöhnliche Flieder"],
    english: ["lilac", "common lilac"],
    wiki_de: "https://de.wikipedia.org/wiki/Gemeiner_Flieder",
    wiki_en: "https://en.wikipedia.org/wiki/Syringa_vulgaris",
  },
  {
    file_name: "Theophil_081",
    scientific_name: "Populus nigra",
    german: ["Schwarz-Pappel", "Saarbaum"],
    english: ["black poplar"],
    wiki_de: "https://de.wikipedia.org/wiki/Schwarz-Pappel",
    wiki_en: "https://en.wikipedia.org/wiki/Populus_nigra",
  },
  {
    file_name: "Theophil_082",
    scientific_name: "Borago officinalis",
    german: ["Borretsch", "Boretsch", "Gurkenkraut", "Kukumerkraut"],
    english: ["Borage", "starflower"],
    wiki_de: "https://de.wikipedia.org/wiki/Borretsch",
    wiki_en: "https://en.wikipedia.org/wiki/Borage",
  },
  {
    file_name: "Theophil_083",
    scientific_name: "Lactuca sativa",
    german: ["Gartensalat", "Gartenlattich", "Lattich"],
    english: ["Lettuce"],
    wiki_de: "https://de.wikipedia.org/wiki/Gartensalat",
    wiki_en: "https://en.wikipedia.org/wiki/Lettuce",
  },
  {
    file_name: "Theophil_084",
    scientific_name: "Brassica",
    german: ["Kohl"],
    english: ["cabbages", "mustard plants"],
    wiki_de: "https://de.wikipedia.org/wiki/Kohl",
    wiki_en: "https://en.wikipedia.org/wiki/Brassica",
  },
  {
    file_name: "Theophil_085",
    scientific_name: "Eruca vesicaria",
    german: ["Senfrauke"],
    english: ["Rocket", "arugula", "eruca"],
    wiki_de: "https://de.wikipedia.org/wiki/Senfrauke",
    wiki_en: "https://en.wikipedia.org/wiki/Eruca_vesicaria",
  },
  {
    file_name: "Theophil_086",
    scientific_name: "Betonica",
    german: ["Betonien"],
    english: ["Betonica"],
    wiki_de: "https://en.wikipedia.org/wiki/Betonica",
    wiki_en: "https://en.wikipedia.org/wiki/Betonica",
  },
  {
    file_name: "Theophil_088",
    scientific_name: "Scabiosa",
    german: ["Skabiosen"],
    english: ["scabious", "pincushion flowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Skabiosen",
    wiki_en: "https://en.wikipedia.org/wiki/Scabiosa",
  },
  {
    file_name: "Theophil_092",
    scientific_name: "Cucumis sativus",
    german: ["Gurke"],
    english: ["Cucumber"],
    wiki_de: "https://de.wikipedia.org/wiki/Gurke",
    wiki_en: "https://en.wikipedia.org/wiki/Cucumber",
  },
  {
    file_name: "Theophil_093",
    scientific_name: "Cucurbita",
    german: ["Kürbisse"],
    english: ["squash", "pumpkin", "gourd"],
    wiki_de: "https://de.wikipedia.org/wiki/K%C3%BCrbisse",
    wiki_en: "https://en.wikipedia.org/wiki/Cucurbita",
  },
  {
    file_name: "Theophil_095",
    scientific_name: "Cucurbita",
    german: ["Kürbisse"],
    english: ["squash", "pumpkin", "gourd"],
    wiki_de: "https://de.wikipedia.org/wiki/K%C3%BCrbisse",
    wiki_en: "https://en.wikipedia.org/wiki/Cucurbita",
  },
  {
    file_name: "Theophil_094",
    scientific_name: "Tussilago farfara",
    german: [
      "Huflattich",
      "Eselslattich",
      "Ackerlatsche",
      "Rosshuf",
      "Eselstappe",
      "Fohlenfuß",
      "Hufblatt",
      "Zieglerblume",
    ],
    english: ["coltsfoot"],
    wiki_de: "https://de.wikipedia.org/wiki/Huflattich",
    wiki_en: "https://en.wikipedia.org/wiki/Tussilago",
  },
  {
    file_name: "Theophil_097",
    scientific_name: "Alcea",
    german: ["Stockrosen", "Stockmalve"],
    english: ["hollyhocks"],
    wiki_de: "https://de.wikipedia.org/wiki/Stockrosen",
    wiki_en: "https://en.wikipedia.org/wiki/Alcea",
  },
  {
    file_name: "Theophil_098",
    scientific_name: "Jacobaea vulgaris",
    german: [
      "Jakobs-Greiskraut",
      "Jakob-Greiskraut",
      "Jakobs-Kreuzkraut",
      "Jakobskraut",
    ],
    english: [
      "ragwort",
      "stinking willie",
      "tansy ragwort",
      "benweed",
      "St. James-wort",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Jakobs-Greiskraut",
    wiki_en: "https://en.wikipedia.org/wiki/Jacobaea_vulgaris",
  },
  {
    file_name: "Theophil_099",
    scientific_name: "Euphorbia characias",
    german: ["Palisaden-Wolfsmilch"],
    english: ["Mediterranean spurge", "Albanian spurge"],
    wiki_de: "https://de.wikipedia.org/wiki/Palisaden-Wolfsmilch",
    wiki_en: "https://en.wikipedia.org/wiki/Euphorbia_characias",
  },
  {
    file_name: "Theophil_100",
    scientific_name: "Lysimachia",
    german: ["Gilbweiderich", "Gelbweiderich", "Felberich"],
    english: ["loosestrife"],
    wiki_de: "https://de.wikipedia.org/wiki/Gilbweiderich",
    wiki_en: "https://en.wikipedia.org/wiki/Lysimachia",
  },
  {
    file_name: "Theophil_101",
    scientific_name: "Aconitum napellus",
    german: ["Blaue Eisenhut"],
    english: ["monk's-hood", "aconite", "wolfsbane"],
    wiki_de: "https://de.wikipedia.org/wiki/Blauer_Eisenhut",
    wiki_en: "https://en.wikipedia.org/wiki/Aconitum_napellus",
  },
  {
    file_name: "Theophil_102",
    scientific_name: "Humulus lupulus",
    german: ["Echter Hopfen", "Hopfen"],
    english: ["common hop", "hop"],
    wiki_de: "https://de.wikipedia.org/wiki/Echter_Hopfen",
    wiki_en: "https://en.wikipedia.org/wiki/Humulus_lupulus",
  },
  {
    file_name: "Theophil_103",
    scientific_name: "Geranium",
    german: ["Storchschnäbel", "Geranien"],
    english: ["geraniums", "cranesbills"],
    wiki_de: "https://de.wikipedia.org/wiki/Storchschn%C3%A4bel",
    wiki_en: "https://en.wikipedia.org/wiki/Geranium",
  },
  {
    file_name: "Theophil_104",
    scientific_name: "Helleborus niger",
    german: ["Schneerose", "Christrose", "Schwarze Nieswurz"],
    english: ["Christmas rose", "black hellebore"],
    wiki_de: "https://de.wikipedia.org/wiki/Schneerose",
    wiki_en: "https://en.wikipedia.org/wiki/Helleborus_niger",
  },
  {
    file_name: "Theophil_106",
    scientific_name: "Seseli libanotis",
    german: ["Heilwurz", "Berg-Heilwurz"],
    english: ["moon carrot", "mountain stone-parsley", "säfferot"],
    wiki_de: "https://de.wikipedia.org/wiki/Heilwurz",
    wiki_en: "https://en.wikipedia.org/wiki/Seseli_libanotis",
  },
  {
    file_name: "Theophil_107",
    scientific_name: "Vitis",
    german: ["Weinreben", "Reben"],
    english: ["grapevines", "grapes", "grape"],
    wiki_de: "https://de.wikipedia.org/wiki/Weinreben",
    wiki_en: "https://en.wikipedia.org/wiki/Vitis",
  },
  {
    file_name: "Theophil_108",
    scientific_name: "Ficus carica",
    german: ["Echte Feige", "Feige"],
    english: ["common fig", "fig"],
    wiki_de: "https://de.wikipedia.org/wiki/Echte_Feige",
    wiki_en: "https://en.wikipedia.org/wiki/Common_fig",
  },
  {
    file_name: "Theophil_109",
    scientific_name: "Antirrhinum",
    german: ["Löwenmäuler", "Löwenmäulchen"],
    english: ["dragon flowers", "snapdragons"],
    wiki_de: "https://de.wikipedia.org/wiki/L%C3%B6wenm%C3%A4uler",
    wiki_en: "https://en.wikipedia.org/wiki/Antirrhinum",
  },
  {
    file_name: "Theophil_110",
    scientific_name: "Erysimum cheiri",
    german: ["Goldlack"],
    english: ["wallflower"],
    wiki_de: "https://de.wikipedia.org/wiki/Goldlack",
    wiki_en: "https://en.wikipedia.org/wiki/Erysimum_cheiri",
  },
  {
    file_name: "Theophil_114",
    scientific_name: "Hyoscyamus",
    german: ["Bilsenkräuter"],
    english: ["henbanes"],
    wiki_de: "https://de.wikipedia.org/wiki/Bilsenkr%C3%A4uter",
    wiki_en: "https://en.wikipedia.org/wiki/Hyoscyamus",
  },
  {
    file_name: "Theophil_115",
    scientific_name: "Vicia",
    german: ["Wicken"],
    english: ["vetches"],
    wiki_de: "https://de.wikipedia.org/wiki/Wicken_(Vicia)",
    wiki_en: "https://en.wikipedia.org/wiki/Potentilla",
  },
  {
    file_name: "Theophil_116",
    scientific_name: "Agrimonia",
    german: ["Odermennige"],
    english: ["agrimony"],
    wiki_de: "https://de.wikipedia.org/wiki/Odermennige",
    wiki_en: "https://en.wikipedia.org/wiki/Agrimonia",
  },
  {
    file_name: "Theophil_117",
    scientific_name: "Potentilla",
    german: ["Fingerkräuter"],
    english: [
      "cinquefoils",
      "five fingers",
      "silverweeds",
      "tormentils",
      "barren strawberries",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Fingerkr%C3%A4uter",
    wiki_en: "https://en.wikipedia.org/wiki/Potentilla",
  },
  {
    file_name: "Theophil_120",
    scientific_name: "Heracleum sphondylium",
    german: ["Wiesen-Bärenklau", "Gemeine Bärenklau", "Bärenklau"],
    english: ["hogweed", "common hogweed", "cow parsnip", "eltrot"],
    wiki_de: "https://de.wikipedia.org/wiki/Wiesen-B%C3%A4renklau",
    wiki_en: "https://en.wikipedia.org/wiki/Heracleum_sphondylium",
  },
  {
    file_name: "Theophil_123",
    scientific_name: "Asparagus officinalis",
    german: ["Spargel", "Gemüsespargel", "Gemeiner Spargel"],
    english: ["asparagus", "garden asparagus", "sparrow grass"],
    wiki_de: "https://de.wikipedia.org/wiki/Gem%C3%BCsespargel",
    wiki_en: "https://en.wikipedia.org/wiki/Asparagus",
  },
  {
    file_name: "Theophil_124",
    scientific_name: "Foeniculum vulgare",
    german: ["Fenchel"],
    english: ["Fennel"],
    wiki_de: "https://de.wikipedia.org/wiki/Fenchel",
    wiki_en: "https://en.wikipedia.org/wiki/Fennel",
  },
  {
    file_name: "Theophil_126",
    scientific_name: "Achillea millefolium",
    german: ["Gemeine Schafgarbe", "Gewöhnliche Schafgarbe"],
    english: ["yarrow", "common yarrow"],
    wiki_de: "https://de.wikipedia.org/wiki/Gemeine_Schafgarbe",
    wiki_en: "https://en.wikipedia.org/wiki/Achillea_millefolium",
  },
  {
    file_name: "Theophil_127",
    scientific_name: "Carum carvi",
    german: ["Kümmel", "Echter Kümmel", "Wiesen-Kümmel", "Gemeiner Kümmel"],
    english: ["Caraway", "meridian fennel", "Persian cumin"],
    wiki_de: "https://de.wikipedia.org/wiki/Echter_K%C3%BCmmel",
    wiki_en: "https://en.wikipedia.org/wiki/Caraway",
  },
  {
    file_name: "Theophil_128",
    scientific_name: "Sanguisorba officinalis",
    german: ["Große Wiesenknopf", "Groß-Wiesenknopf"],
    english: ["great burnet"],
    wiki_de: "https://de.wikipedia.org/wiki/Gro%C3%9Fer_Wiesenknopf",
    wiki_en: "https://en.wikipedia.org/wiki/Sanguisorba_officinalis",
  },
  {
    file_name: "Theophil_129",
    scientific_name: "Artemisia absinthium",
    german: [
      "Wermut",
      "Echt-Wermut",
      "Wermutkraut",
      "Bitterer Beifuß",
      "Alsem",
    ],
    english: [
      "wormwood",
      "grand wormwood",
      "absinthe",
      "absinthium",
      "absinthe wormwood",
      "mugwort",
      "wermout",
      "wermud",
      "wormit",
      "wormod",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Wermutkraut",
    wiki_en: "https://en.wikipedia.org/wiki/Artemisia_absinthium",
  },
  {
    file_name: "Theophil_130",
    scientific_name: "Artemisia abrotanum",
    german: ["Eberraute"],
    english: ["southernwood", "lad's love", "southern wormwood"],
    wiki_de: "https://de.wikipedia.org/wiki/Eberraute",
    wiki_en: "https://en.wikipedia.org/wiki/Artemisia_abrotanum",
  },
  {
    file_name: "Theophil_134",
    scientific_name: "Colutea",
    german: ["Blasensträucher"],
    english: ["Colutea"],
    wiki_de: "https://de.wikipedia.org/wiki/Blasenstr%C3%A4ucher",
    wiki_en: "https://en.wikipedia.org/wiki/Colutea",
  },
  {
    file_name: "Theophil_135",
    scientific_name: "Vincetoxicum hirundinaria",
    german: ["Schwalbenwurz"],
    english: ["white swallow-wort"],
    wiki_de: "https://de.wikipedia.org/wiki/Schwalbenwurz",
    wiki_en: "https://en.wikipedia.org/wiki/Vincetoxicum_hirundinaria",
  },
  {
    file_name: "Theophil_136",
    scientific_name: "Mentha",
    german: ["Minzen"],
    english: ["mint"],
    wiki_de: "https://de.wikipedia.org/wiki/Minzen",
    wiki_en: "https://en.wikipedia.org/wiki/Mentha",
  },
  {
    file_name: "Theophil_137",
    scientific_name: "Teucrium scordium",
    german: ["Knoblauch-Gamander", "Lauch-Gamander"],
    english: [""],
    wiki_de: "https://de.wikipedia.org/wiki/Knoblauch-Gamander",
    wiki_en: "https://en.wikipedia.org/wiki/Teucrium_scordium",
  },
  {
    file_name: "Theophil_138",
    scientific_name: "Mercurialis",
    german: ["Bingelkräuter"],
    english: ["mercuries"],
    wiki_de: "https://de.wikipedia.org/wiki/Bingelkr%C3%A4uter",
    wiki_en: "https://en.wikipedia.org/wiki/Mercurialis_(plant)",
  },
  {
    file_name: "Theophil_140",
    scientific_name: "Origanum",
    german: ["Dost", "Orant", "Majoran", "Oregano"],
    english: ["marjoram", "oregano"],
    wiki_de: "https://en.wikipedia.org/wiki/Origanum",
    wiki_en: "https://de.wikipedia.org/wiki/Dost_(Gattung)",
  },
  {
    file_name: "Theophil_141",
    scientific_name: "Ocimum basilicum",
    german: ["Basilikum", "Basilie", "Basilienkraut", "Königskraut"],
    english: ["Basil"],
    wiki_de: "https://de.wikipedia.org/wiki/Basilikum",
    wiki_en: "https://en.wikipedia.org/wiki/Basil",
  },
  {
    file_name: "Theophil_142",
    scientific_name: "Calendula",
    german: ["Ringelblumen"],
    english: ["marigolds"],
    wiki_de: "https://de.wikipedia.org/wiki/Ringelblumen",
    wiki_en: "https://en.wikipedia.org/wiki/Calendula",
  },
  {
    file_name: "Theophil_143",
    scientific_name: "Atriplex",
    german: ["Melden"],
    english: ["saltbush", "orache", "orach"],
    wiki_de: "https://de.wikipedia.org/wiki/Melden",
    wiki_en: "https://en.wikipedia.org/wiki/Atriplex",
  },
  {
    file_name: "Theophil_144",
    scientific_name: "Asplenium scolopendrium",
    german: ["Hirschzungenfarn", "Hirschzunge"],
    english: ["hart's-tongue", "hart's-tongue fern"],
    wiki_de: "https://de.wikipedia.org/wiki/Hirschzungenfarn",
    wiki_en: "https://en.wikipedia.org/wiki/Asplenium_scolopendrium",
  },
  {
    file_name: "Theophil_145",
    scientific_name: "Lysimachia nummularia",
    german: ["Pfennigkraut", "Münzkraut", "Pfennig-Gilbweiderich"],
    english: ["moneywort", "creeping jenny", "herb twopence", "twopenny grass"],
    wiki_de: "https://de.wikipedia.org/wiki/Pfennigkraut",
    wiki_en: "https://en.wikipedia.org/wiki/Lysimachia_nummularia",
  },
  {
    file_name: "Theophil_146",
    scientific_name: "Quercus",
    german: ["Eichen"],
    english: ["oak"],
    wiki_de: "https://de.wikipedia.org/wiki/Eichen",
    wiki_en: "https://en.wikipedia.org/wiki/Oak",
  },
];
