johannesDrawing = [
  {
    file_name: "Johannes_A_001",
    scientific_name: "Phoenix dactylifera",
    german: ["Echte Dattelpalme"],
    english: ["Date Palm"],
    wiki_de: "https://de.wikipedia.org/wiki/Echte_Dattelpalme",
    wiki_en: "https://en.wikipedia.org/wiki/Date_palm",
  },
  {
    file_name: "Johannes_A_002",
    scientific_name: "Mandragora",
    german: ["Alraune"],
    english: ["Mandrake"],
    wiki_de: "https://de.wikipedia.org/wiki/Alraunen",
    wiki_en: "https://en.wikipedia.org/wiki/Mandragora_(genus)",
  },
  {
    file_name: "Johannes_A_003",
    scientific_name: "Larix",
    german: ["Lärchen"],
    english: ["Larch"],
    wiki_de: "https://de.wikipedia.org/wiki/L%C3%A4rchen",
    wiki_en: "https://en.wikipedia.org/wiki/Larch",
  },
  {
    file_name: "Johannes_A_004",
    scientific_name: "Laserpitium siler",
    german: ["Berg-Laserkraut", "Bergkümmel"],
    english: ["Laserwort"],
    wiki_de: "https://de.wikipedia.org/wiki/Berg-Laserkraut",
    wiki_en: "https://en.wikipedia.org/wiki/Laserpitium_siler",
  },
  {
    file_name: "Johannes_A_006",
    scientific_name: "Senna alexandrina",
    german: ["Alexandrinische Senna"],
    english: ["Alexandrian senna"],
    wiki_de: "https://de.wikipedia.org/wiki/Alexandrinische_Senna",
    wiki_en: "https://en.wikipedia.org/wiki/Senna_alexandrina",
  },
  {
    file_name: "Johannes_A_007",
    scientific_name: "Hemionitis",
    german: [""],
    english: ["Hemionitis"],
    wiki_de: "https://en.wikipedia.org/wiki/Hemionitis",
    wiki_en: "https://en.wikipedia.org/wiki/Hemionitis",
  },
  {
    file_name: "Johannes_A_008",
    scientific_name: "Phoenix",
    german: ["Dattelpalmen"],
    english: ["Phoenix"],
    wiki_de: "https://de.wikipedia.org/wiki/Dattelpalmen",
    wiki_en: "https://en.wikipedia.org/wiki/Phoenix_(plant)",
  },
  {
    file_name: "Johannes_A_009",
    scientific_name: "Aconitum",
    german: ["Eisenhut", "Sturmhut", "Akonit", "Wolfswurz"],
    english: [
      "aconite",
      "monkshood",
      "wolf's bane",
      "leopard's bane",
      "mouse bane",
      "women's bane",
      "devil's helmet",
      "queen of poisons",
      "blue rocket",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Eisenhut",
    wiki_en: "https://en.wikipedia.org/wiki/Aconitum",
  },
  {
    file_name: "Johannes_A_039",
    scientific_name: "Aconitum",
    german: ["Eisenhut", "Sturmhut", "Akonit", "Wolfswurz"],
    english: [
      "aconite",
      "monkshood",
      "wolf's bane",
      "leopard's bane",
      "mouse bane",
      "women's bane",
      "devil's helmet",
      "queen of poisons",
      "blue rocket",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Eisenhut",
    wiki_en: "https://en.wikipedia.org/wiki/Aconitum",
  },
  {
    file_name: "Johannes_A_025",
    scientific_name: "Aconitum napellus",
    german: ["Blaue Eisenhut"],
    english: ["monk's-hood", "aconite", "wolfsbane"],
    wiki_de: "https://de.wikipedia.org/wiki/Blauer_Eisenhut",
    wiki_en: "https://en.wikipedia.org/wiki/Aconitum_napellus",
  },
  {
    file_name: "Johannes_A_010",
    scientific_name: "Orchidaceae",
    german: ["Orchideen"],
    english: ["orchid"],
    wiki_de: "https://de.wikipedia.org/wiki/Orchideen",
    wiki_en: "https://en.wikipedia.org/wiki/Orchidaceae",
  },
  {
    file_name: "Johannes_A_015",
    scientific_name: "Orchidaceae",
    german: ["Orchideen"],
    english: ["orchid"],
    wiki_de: "https://de.wikipedia.org/wiki/Orchideen",
    wiki_en: "https://en.wikipedia.org/wiki/Orchidaceae",
  },
  {
    file_name: "Johannes_A_018",
    scientific_name: "Orchidaceae",
    german: ["Orchideen"],
    english: ["orchid"],
    wiki_de: "https://de.wikipedia.org/wiki/Orchideen",
    wiki_en: "https://en.wikipedia.org/wiki/Orchidaceae",
  },
  {
    file_name: "Johannes_A_024",
    scientific_name: "Orchidaceae",
    german: ["Orchideen"],
    english: ["orchid"],
    wiki_de: "https://de.wikipedia.org/wiki/Orchideen",
    wiki_en: "https://en.wikipedia.org/wiki/Orchidaceae",
  },
  {
    file_name: "Johannes_A_016",
    scientific_name: "Tulipa",
    german: ["Tulpen"],
    english: ["Tulip"],
    wiki_de: "https://de.wikipedia.org/wiki/Tulpen",
    wiki_en: "https://en.wikipedia.org/wiki/Tulip",
  },
  {
    file_name: "Johannes_B_046",
    scientific_name: "Tulipa",
    german: ["Tulpen"],
    english: ["Tulip"],
    wiki_de: "https://de.wikipedia.org/wiki/Tulpen",
    wiki_en: "https://en.wikipedia.org/wiki/Tulip",
  },
  {
    file_name: "Johannes_A_019",
    scientific_name: "Laurus nobilis",
    german: ["Edler Lorbeer", "Gewürzlorbeer", "Lorbeer"],
    english: [
      "bay tree",
      "bay laurel",
      "sweet bay",
      "true laurel",
      "Grecian laurel",
      "laurel",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Echter_Lorbeer",
    wiki_en: "https://en.wikipedia.org/wiki/Laurus_nobilis",
  },
  {
    file_name: "Johannes_A_023",
    scientific_name: "Lunaria",
    german: [
      "Silberblatt",
      "Silbertaler",
      "Silberling",
      "Judaspfennig",
      "Mondviole",
    ],
    english: ["honesty"],
    wiki_de: "https://de.wikipedia.org/wiki/Silberbl%C3%A4tter",
    wiki_en: "https://en.wikipedia.org/wiki/Lunaria",
  },
  {
    file_name: "Johannes_A_026",
    scientific_name: "Nerium oleander",
    german: ["Oleander", "Nerium"],
    english: ["oleander", "nerium"],
    wiki_de: "https://de.wikipedia.org/wiki/Oleander",
    wiki_en: "https://en.wikipedia.org/wiki/Nerium",
  },
  {
    file_name: "Johannes_A_027",
    scientific_name: "Antirrhinum",
    german: ["Löwenmäuler", "Löwenmäulchen"],
    english: ["dragon flowers", "snapdragons"],
    wiki_de: "https://de.wikipedia.org/wiki/L%C3%B6wenm%C3%A4uler",
    wiki_en: "https://en.wikipedia.org/wiki/Antirrhinum",
  },
  {
    file_name: "Johannes_A_032",
    scientific_name: "Aquilegia",
    german: ["Akeleien"],
    english: ["granny's bonnet", "columbine"],
    wiki_de: "https://de.wikipedia.org/wiki/Akeleien",
    wiki_en: "https://en.wikipedia.org/wiki/Aquilegia",
  },
  {
    file_name: "Johannes_A_033",
    scientific_name: "Staphisagria macrosperma",
    german: [
      "Stephanskraut",
      "Mittelmeer-Rittersporn",
      "Stephanskorn",
      "Giftiger Rittersporn",
      "Läusepfeffer",
      "Lauswurz",
      "Läusezahn",
      "Läusesamen",
      "Kräusesamen",
    ],
    english: ["stavesacre"],
    wiki_de: "https://de.wikipedia.org/wiki/Stephanskraut",
    wiki_en: "https://en.wikipedia.org/wiki/Staphisagria_macrosperma",
  },
  {
    file_name: "Johannes_A_034",
    scientific_name: "Pancratium maritimum",
    german: ["Dünen-Trichternarzisse"],
    english: ["sea daffodil"],
    wiki_de: "https://de.wikipedia.org/wiki/D%C3%BCnen-Trichternarzisse",
    wiki_en: "https://en.wikipedia.org/wiki/Pancratium_maritimum",
  },
  {
    file_name: "Johannes_A_044",
    scientific_name: "Pancratium maritimum",
    german: ["Dünen-Trichternarzisse"],
    english: ["sea daffodil"],
    wiki_de: "https://de.wikipedia.org/wiki/D%C3%BCnen-Trichternarzisse",
    wiki_en: "https://en.wikipedia.org/wiki/Pancratium_maritimum",
  },
  {
    file_name: "Johannes_A_035",
    scientific_name: "Fumaria",
    german: ["Erdrauch"],
    english: ["fumitory", "fumewort"],
    wiki_de: "https://de.wikipedia.org/wiki/Erdrauch",
    wiki_en: "https://en.wikipedia.org/wiki/Fumaria",
  },
  {
    file_name: "Johannes_A_036",
    scientific_name: "Cistus",
    german: ["Zistrosen"],
    english: ["rockrose"],
    wiki_de: "https://de.wikipedia.org/wiki/Zistrosen",
    wiki_en: "https://en.wikipedia.org/wiki/Cistus",
  },
  {
    file_name: "Johannes_A_037",
    scientific_name: "Seseli",
    german: ["Bergfenchel", "Sesel"],
    english: ["Seseli"],
    wiki_de: "https://de.wikipedia.org/wiki/Bergfenchel",
    wiki_en: "https://en.wikipedia.org/wiki/Seseli",
  },
  {
    file_name: "Johannes_A_045",
    scientific_name: "Pimpinella anisum",
    german: ["Anis"],
    english: ["Anise", "aniseed", "anix"],
    wiki_de: "https://de.wikipedia.org/wiki/Anis",
    wiki_en: "https://en.wikipedia.org/wiki/Anise",
  },
  {
    file_name: "Johannes_A_048",
    scientific_name: "Platanus",
    german: ["Platanen"],
    english: ["planes", "plane trees"],
    wiki_de: "https://de.wikipedia.org/wiki/Platanen",
    wiki_en: "https://en.wikipedia.org/wiki/Platanus",
  },
  {
    file_name: "Johannes_A_099",
    scientific_name: "Platanus",
    german: ["Platanen"],
    english: ["planes", "plane trees"],
    wiki_de: "https://de.wikipedia.org/wiki/Platanen",
    wiki_en: "https://en.wikipedia.org/wiki/Platanus",
  },
  {
    file_name: "Johannes_A_049",
    scientific_name: "Punica granatum",
    german: ["Granatapfel"],
    english: ["pomegranate"],
    wiki_de: "https://de.wikipedia.org/wiki/Granatapfel",
    wiki_en: "https://en.wikipedia.org/wiki/Pomegranate",
  },
  {
    file_name: "Johannes_A_050",
    scientific_name: "Citrus",
    german: ["Zitruspflanzen"],
    english: ["citrus"],
    wiki_de: "https://de.wikipedia.org/wiki/Zitruspflanzen",
    wiki_en: "https://en.wikipedia.org/wiki/Citrus",
  },
  {
    file_name: "Johannes_A_051",
    scientific_name: "Citrus",
    german: ["Zitruspflanzen"],
    english: ["citrus"],
    wiki_de: "https://de.wikipedia.org/wiki/Zitruspflanzen",
    wiki_en: "https://en.wikipedia.org/wiki/Citrus",
  },
  {
    file_name: "Johannes_A_052",
    scientific_name: "Trigonella foenum-graecum",
    german: ["Bockshornklee"],
    english: ["Fenugreek", "methi"],
    wiki_de: "https://de.wikipedia.org/wiki/Bockshornklee",
    wiki_en: "https://en.wikipedia.org/wiki/Fenugreek",
  },
  {
    file_name: "Johannes_A_055",
    scientific_name: "Chrysanthemum",
    german: ["Chrysanthemen"],
    english: ["Chrysanthemums", "mums", "chrysanths"],
    wiki_de: "https://de.wikipedia.org/wiki/Chrysanthemen",
    wiki_en: "https://en.wikipedia.org/wiki/Chrysanthemum",
  },
  {
    file_name: "Johannes_A_057",
    scientific_name: "Tribulus terrestris",
    german: ["Erdburzeldorn", "Erdsternchen", "Erdstachelnuss"],
    english: [
      "goat's-head",
      "bindii",
      "bullhead",
      "burra gokharu",
      "bhakhdi",
      "caltrop",
      "small caltrops",
      "cat's-head",
      "devil's eyelashes",
      "devil's-thorn",
      "devil's-weed",
      "puncture vine",
      "tackweed",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Erd-Burzeldorn",
    wiki_en: "https://en.wikipedia.org/wiki/Tribulus_terrestris",
  },
  {
    file_name: "Johannes_A_058",
    scientific_name: "Cuminum cyminum",
    german: ["Kreuzkümmel", "Kumin", "Römischer Kümmel"],
    english: ["cumin"],
    wiki_de: "https://de.wikipedia.org/wiki/Kreuzk%C3%BCmmel",
    wiki_en: "https://en.wikipedia.org/wiki/Cumin",
  },
  {
    file_name: "Johannes_A_059",
    scientific_name: "Vitex agnus-castus",
    german: ["Mönchspfeffer", "Keuschbaum", "Keuschlamm"],
    english: [
      "vitex",
      "chaste tree",
      "chasteberry",
      "Abraham's balm",
      "lilac chastetree",
      "monk's pepper",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/M%C3%B6nchspfeffer",
    wiki_en: "https://en.wikipedia.org/wiki/Vitex_agnus-castus",
  },
  {
    file_name: "Johannes_A_060",
    scientific_name: "Tanacetum parthenium",
    german: ["Mutterkraut", "Falsche Kamille", "Zierkamille", "Fieberkraut"],
    english: ["feverfew"],
    wiki_de: "https://de.wikipedia.org/wiki/Mutterkraut",
    wiki_en: "https://en.wikipedia.org/wiki/Tanacetum_parthenium",
  },
  {
    file_name: "Johannes_A_063",
    scientific_name: "Morus alba",
    german: ["Weiße Maulbeere"],
    english: ["white mulberry", "common mulberry", "silkworm mulberry"],
    wiki_de: "https://de.wikipedia.org/wiki/Wei%C3%9Fe_Maulbeere",
    wiki_en: "https://en.wikipedia.org/wiki/Morus_alba",
  },
  {
    file_name: "Johannes_A_064",
    scientific_name: "Jasminum",
    german: ["Jasmin"],
    english: ["Jasmine"],
    wiki_de: "https://de.wikipedia.org/wiki/Jasminum",
    wiki_en: "https://en.wikipedia.org/wiki/Jasmine",
  },
  {
    file_name: "Johannes_A_065",
    scientific_name: "Jasminum",
    german: ["Jasmin"],
    english: ["Jasmine"],
    wiki_de: "https://de.wikipedia.org/wiki/Jasminum",
    wiki_en: "https://en.wikipedia.org/wiki/Jasmine",
  },
  {
    file_name: "Johannes_A_069",
    scientific_name: "Thymus",
    german: ["Thymiane", "Quendel"],
    english: ["thymes"],
    wiki_de: "https://de.wikipedia.org/wiki/Thymiane",
    wiki_en: "https://en.wikipedia.org/wiki/Thymus_(plant)",
  },
  {
    file_name: "Johannes_A_070",
    scientific_name: "Arbutus",
    german: [
      "Erdbeerbäume",
      "westlicher Hagapfel",
      "Landbeere",
      "Meerkirsche",
      "Sandbeere",
    ],
    english: ["madrones", "madronas", "arbutus"],
    wiki_de: "https://de.wikipedia.org/wiki/Erdbeerb%C3%A4ume",
    wiki_en: "https://en.wikipedia.org/wiki/Arbutus",
  },
  {
    file_name: "Johannes_A_071",
    scientific_name: "Ruscus aculeatus",
    german: ["Stechender Mäusedorn", "Stacheliger Mäusedorn", "Dornmyrte"],
    english: ["butcher's-broom"],
    wiki_de: "https://de.wikipedia.org/wiki/Stechender_M%C3%A4usedorn",
    wiki_en: "https://en.wikipedia.org/wiki/Ruscus_aculeatus",
  },
  {
    file_name: "Johannes_A_072",
    scientific_name: "Aristolochia",
    german: ["Pfeifenwinden", "Osterluzei"],
    english: ["birthwort", "pipevine", "Dutchman's pipe"],
    wiki_de: "https://de.wikipedia.org/wiki/Pfeifenblumen",
    wiki_en: "https://en.wikipedia.org/wiki/Aristolochia",
  },
  {
    file_name: "Johannes_A_073",
    scientific_name: "Viola tricolor",
    german: [
      "Wilde Stiefmütterchen",
      "Ackerveilchen",
      "Muttergottesschuh",
      "Mädchenaugen",
      "Schöngesicht",
      "Liebesgesichtli",
      "Christusauge",
      "Stiefmütterchen",
    ],
    english: ["wild pansy", "heartsease", "heart's ease", "heart's delight"],
    wiki_de: "https://de.wikipedia.org/wiki/Wildes_Stiefm%C3%BCtterchen",
    wiki_en: "https://en.wikipedia.org/wiki/Viola_tricolor",
  },
  {
    file_name: "Johannes_A_079",
    scientific_name: "Laburnum",
    german: ["Goldregen", "Bohnenbaum", "Goldrausch", "Gelbstrauch"],
    english: ["golden chain", "golden rain"],
    wiki_de: "https://de.wikipedia.org/wiki/Goldregen_(Pflanze)",
    wiki_en: "https://en.wikipedia.org/wiki/Laburnum",
  },
  {
    file_name: "Johannes_A_080",
    scientific_name: "Ilex",
    german: [
      "Stechpalmen",
      "Hülsen",
      "Hulst",
      "Winterbeeren",
      "Christdorn",
      "Schradler",
    ],
    english: ["holly"],
    wiki_de: "https://de.wikipedia.org/wiki/Stechpalmen",
    wiki_en: "https://en.wikipedia.org/wiki/Holly",
  },
  {
    file_name: "Johannes_A_081",
    scientific_name: "Populus alba",
    german: ["Silber-Pappel", "Weiß-Pappel"],
    english: ["silver poplar", "silverleaf poplar", "white poplar"],
    wiki_de: "https://de.wikipedia.org/wiki/Silber-Pappel",
    wiki_en: "https://en.wikipedia.org/wiki/Populus_alba",
  },
  {
    file_name: "Johannes_A_082",
    scientific_name: "Pistacia terebinthus",
    german: ["Terpentin-Pistazie"],
    english: ["terebinth"],
    wiki_de: "https://de.wikipedia.org/wiki/Terpentin-Pistazie",
    wiki_en: "https://en.wikipedia.org/wiki/Terebinth",
  },
  {
    file_name: "Johannes_A_089",
    scientific_name: "Juniperus oxycedrus",
    german: ["Stech-Wacholder"],
    english: [
      "Cade",
      "cade juniper",
      "prickly juniper",
      "prickly cedar",
      "sharp cedar",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Stech-Wacholder",
    wiki_en: "https://en.wikipedia.org/wiki/Juniperus_oxycedrus",
  },
  {
    file_name: "Johannes_A_091",
    scientific_name: "Verbascum",
    german: ["Königskerzen"],
    english: ["mullein"],
    wiki_de: "https://de.wikipedia.org/wiki/K%C3%B6nigskerzen",
    wiki_en: "https://en.wikipedia.org/wiki/Verbascum",
  },
  {
    file_name: "Johannes_A_094",
    scientific_name: "Asphodelus",
    german: ["Affodill"],
    english: ["asphodel"],
    wiki_de: "https://de.wikipedia.org/wiki/Affodill",
    wiki_en: "https://en.wikipedia.org/wiki/Asphodelus",
  },
  {
    file_name: "Johannes_A_095",
    scientific_name: "Asphodelus",
    german: ["Affodill"],
    english: ["asphodel"],
    wiki_de: "https://de.wikipedia.org/wiki/Affodill",
    wiki_en: "https://en.wikipedia.org/wiki/Asphodelus",
  },
  {
    file_name: "Johannes_A_096",
    scientific_name: "Asphodelus",
    german: ["Affodill"],
    english: ["asphodel"],
    wiki_de: "https://de.wikipedia.org/wiki/Affodill",
    wiki_en: "https://en.wikipedia.org/wiki/Asphodelus",
  },
  {
    file_name: "Johannes_A_097",
    scientific_name: "Coix lacryma-jobi",
    german: ["Hiobsträne", "Hiobstränengras", "Chinesische Perlgerste"],
    english: ["Job's tears", "adlay", "adlay millet", "Chinese pearl barley"],
    wiki_de: "https://de.wikipedia.org/wiki/Hiobstr%C3%A4ne",
    wiki_en: "https://en.wikipedia.org/wiki/Job%27s_tears",
  },
  {
    file_name: "Johannes_B_015",
    scientific_name: "Euphorbia characias",
    german: ["Palisaden-Wolfsmilch"],
    english: ["Mediterranean spurge", "Albanian spurge"],
    wiki_de: "https://de.wikipedia.org/wiki/Palisaden-Wolfsmilch",
    wiki_en: "https://en.wikipedia.org/wiki/Euphorbia_characias",
  },
  {
    file_name: "Johannes_B_016",
    scientific_name: "Euphorbia paralias",
    german: ["Strand-Wolfsmilch", "Dünen-Wolfsmilch"],
    english: ["sea spurge"],
    wiki_de: "https://de.wikipedia.org/wiki/Strand-Wolfsmilch",
    wiki_en: "https://en.wikipedia.org/wiki/Euphorbia_paralias",
  },
  {
    file_name: "Johannes_B_021",
    scientific_name: "Styrax",
    german: ["Storaxbäume"],
    english: ["storax", "snowbell"],
    wiki_de: "https://de.wikipedia.org/wiki/Storaxb%C3%A4ume",
    wiki_en: "https://en.wikipedia.org/wiki/Styrax",
  },
  {
    file_name: "Johannes_B_022",
    scientific_name: "Rhamnus",
    german: ["Kreuzdorn"],
    english: ["buckthorns"],
    wiki_de: "https://de.wikipedia.org/wiki/Kreuzdorn",
    wiki_en: "https://en.wikipedia.org/wiki/Rhamnus_(plant)",
  },
  {
    file_name: "Johannes_B_023",
    scientific_name: "Rhamnus",
    german: ["Kreuzdorn"],
    english: ["buckthorns"],
    wiki_de: "https://de.wikipedia.org/wiki/Kreuzdorn",
    wiki_en: "https://en.wikipedia.org/wiki/Rhamnus_(plant)",
  },
  {
    file_name: "Johannes_B_024",
    scientific_name: "Rhamnus",
    german: ["Kreuzdorn"],
    english: ["buckthorns"],
    wiki_de: "https://de.wikipedia.org/wiki/Kreuzdorn",
    wiki_en: "https://en.wikipedia.org/wiki/Rhamnus_(plant)",
  },
  {
    file_name: "Johannes_B_027",
    scientific_name: "Gentianella",
    german: ["Kranzenziane"],
    english: ["dwarf gentians"],
    wiki_de: "https://de.wikipedia.org/wiki/Kranzenziane",
    wiki_en: "https://en.wikipedia.org/wiki/Gentianella",
  },
  {
    file_name: "Johannes_A_100",
    scientific_name: "Myrtus",
    german: [""],
    english: ["myrtle"],
    wiki_de: "https://en.wikipedia.org/wiki/Myrtus",
    wiki_en: "https://en.wikipedia.org/wiki/Myrtus",
  },
  {
    file_name: "Johannes_B_032",
    scientific_name: "Myrtus",
    german: [""],
    english: ["myrtle"],
    wiki_de: "https://en.wikipedia.org/wiki/Myrtus",
    wiki_en: "https://en.wikipedia.org/wiki/Myrtus",
  },
  {
    file_name: "Johannes_B_028",
    scientific_name: "Gentiana",
    german: ["Enziane"],
    english: ["Gentiana"],
    wiki_de: "https://de.wikipedia.org/wiki/Enziane",
    wiki_en: "https://en.wikipedia.org/wiki/Gentiana",
  },
  {
    file_name: "Johannes_B_033",
    scientific_name: "Gentiana",
    german: ["Enziane"],
    english: ["Gentiana"],
    wiki_de: "https://de.wikipedia.org/wiki/Enziane",
    wiki_en: "https://en.wikipedia.org/wiki/Gentiana",
  },
  {
    file_name: "Johannes_B_039",
    scientific_name: "Ambrosia",
    german: ["Traubenkräuter", "Ambrosien"],
    english: ["Ragweeds", "bursages", "burrobrushes"],
    wiki_de: "https://de.wikipedia.org/wiki/Traubenkräuter",
    wiki_en: "https://en.wikipedia.org/wiki/Ragweed",
  },
  {
    file_name: "Johannes_A_040",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_A_042",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_A_093",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_B_007",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_B_008",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_B_009",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_B_018",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_B_064",
    scientific_name: "Anemone",
    german: ["Windröschen"],
    english: ["windflowers"],
    wiki_de: "https://de.wikipedia.org/wiki/Windr%C3%B6schen",
    wiki_en: "https://en.wikipedia.org/wiki/Anemone",
  },
  {
    file_name: "Johannes_B_011",
    scientific_name: "Eryngium",
    german: ["Mannstreu", "Edeldistel"],
    english: ["eryngo", "sea holly"],
    wiki_de: "https://de.wikipedia.org/wiki/Mannstreu",
    wiki_en: "https://en.wikipedia.org/wiki/Eryngium",
  },
  {
    file_name: "Johannes_B_042",
    scientific_name: "Eryngium maritimum",
    german: ["Stranddistel", "Meer-Mannstreu"],
    english: ["sea holly", "seaside eryngo"],
    wiki_de: "https://de.wikipedia.org/wiki/Stranddistel",
    wiki_en: "https://en.wikipedia.org/wiki/Eryngium_maritimum",
  },
  {
    file_name: "Johannes_B_043",
    scientific_name: "Canna",
    german: ["Blumenrohr"],
    english: ["canna", "canna lily"],
    wiki_de: "https://de.wikipedia.org/wiki/Blumenrohr",
    wiki_en: "https://en.wikipedia.org/wiki/Canna_(plant)",
  },
  {
    file_name: "Johannes_B_111",
    scientific_name: "Canna indica",
    german: [
      "Indisches Blumenrohr",
      "Essbare Canna",
      "Achira",
      "Kapacho",
      "Australische Pfeilwurz",
    ],
    english: [
      "canna",
      "Indian shot",
      "African arrowroot",
      "edible canna",
      "purple arrowroot",
      "Sierra Leone arrowroot",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/Indisches_Blumenrohr",
    wiki_en: "https://en.wikipedia.org/wiki/Canna_indica",
  },
  {
    file_name: "Johannes_B_044",
    scientific_name: "Peganum harmala",
    german: [
      "Steppenraute",
      "Harmelraute",
      "Harmalkraut",
      "Syrische Steppenraute",
      "Afrikanische Raute",
    ],
    english: ["wild rue", "Syrian rue", "African rue", "esfand", "harmel"],
    wiki_de: "https://de.wikipedia.org/wiki/Steppenraute",
    wiki_en: "https://en.wikipedia.org/wiki/Peganum_harmala",
  },
  {
    file_name: "Johannes_B_045",
    scientific_name: "Astragalus gummifer",
    german: ["Traganth"],
    english: ["tragacanth", "gum tragacanth milkvetch"],
    wiki_de: "https://de.wikipedia.org/wiki/Traganth",
    wiki_en: "https://en.wikipedia.org/wiki/Astragalus_gummifer",
  },
  {
    file_name: "Johannes_B_047",
    scientific_name: "Ornithogalum",
    german: ["Milchsterne"],
    english: ["Star-of-Bethlehem"],
    wiki_de: "https://de.wikipedia.org/wiki/Milchsterne",
    wiki_en: "https://en.wikipedia.org/wiki/Ornithogalum",
  },
  {
    file_name: "Johannes_A_012",
    scientific_name: "Narcissus",
    german: ["Narzissen", "Osterglocke"],
    english: ["daffodil", "narcissus", "jonquil"],
    wiki_de: "https://de.wikipedia.org/wiki/Narzissen",
    wiki_en: "https://en.wikipedia.org/wiki/Narcissus_(plant)",
  },
  {
    file_name: "Johannes_A_013",
    scientific_name: "Narcissus",
    german: ["Narzissen", "Osterglocke"],
    english: ["daffodil", "narcissus", "jonquil"],
    wiki_de: "https://de.wikipedia.org/wiki/Narzissen",
    wiki_en:
      "https://en.wikipedia.org/wiki/https://de.wikipedia.org/wiki/SommerwurzenNarcissus_(plahttps://en.wikipedia.org/wiki/Orobanchent)",
  },
  {
    file_name: "Johannes_A_014",
    scientific_name: "Narcissus",
    german: ["Narzissen", "Osterglocke"],
    english: ["daffodil", "narcissus", "jonquil"],
    wiki_de: "https://de.wikipedia.org/wiki/Narzissen",
    wiki_en:
      "https://en.wikipedia.org/wiki/https://de.wikipedia.org/https://de.wikipedia.org/wiki/Hyazinthenwiki/SommerwurzenNarcissus_(plahttps://en.wikipedia.org/wiki/Orobanchent)",
  },
  {
    file_name: "Johannes_B_048",
    scientific_name: "Narcissus",
    german: ["Narzissen", "Osterglocke"],
    english: ["daffodil", "narcissus", "jonquil"],
    wiki_de: "https://de.wikipedia.org/wiki/Narzissen",
    wiki_en:
      "https://en.wikipedia.org/wiki/https://de.wikipedia.org/https://de.wikipedia.org/wiki/Hyazinthenwiki/SommerwurzenNarcissus_(plahttps://en.wikipedia.org/wiki/Orobanchent)",
  },
  {
    file_name: "Johannes_B_049",
    scientific_name: "Orobanche",
    german: ["Sommerwurzen"],
    english: ["broomrape"],
    wiki_de: "https://de.wikipedia.org/wiki/Sommerwurzen",
    wiki_en:
      "https://en.wikipedia.org/https://de.wikipedia.org/wiki/Hyazinthenwiki/Orobanche",
  },
  {
    file_name: "Johannes_A_038",
    scientific_name: "Hyacinthus",
    german: ["Hyazinthen"],
    english: ["hyacinths"],
    wiki_de: "https://de.wikipedia.org/wiki/Hyazinthen",
    wiki_en: "https://en.wikipedia.org/wiki/Hyacinth_(plant)",
  },
  {
    file_name: "Johannes_B_050",
    scientific_name: "Hyacinthus",
    german: ["Hyazinthen"],
    english: ["hyacinths"],
    wiki_de: "https://de.wikipedia.org/wiki/Hyazinthen",
    wiki_en: "https://en.wikipedia.org/wiki/Hyacinth_(plant)",
  },
  {
    file_name: "Johannes_B_063",
    scientific_name: "Hyacinthus",
    german: ["Hyazinthen"],
    english: ["hyacinths"],
    wiki_de: "https://de.wikipedia.org/wiki/Hyazinthen",
    wiki_en: "https://en.wikipedia.org/wiki/Hyacinth_(plant)",
  },
  {
    file_name: "Johannes_B_056",
    scientific_name: "Rhus coriaria",
    german: ["Gerber-Sumach", "Sizilianischer Sumach", "Färberbaum"],
    english: ["Sicilian sumac", "tanner's sumach", "elm-leaved sumach"],
    wiki_de: "https://de.wikipedia.org/wiki/Gerber-Sumach",
    wiki_en: "https://en.wikipedia.org/wiki/Rhus_coriaria",
  },
  {
    file_name: "Johannes_B_059",
    scientific_name: "Rhaponticum",
    german: [
      "Saflor-Bergscharte",
      "Maralwurzel",
      "Maralpflanze",
      "Hirschwurzel",
    ],
    english: ["Maral root", "Rhaponticum"],
    wiki_de: "https://en.wikipedia.org/wiki/Rhaponticum_carthamoides",
    wiki_en: "https://de.wikipedia.org/wiki/Saflor-Bergscharte",
  },
  {
    file_name: "Johannes_B_060",
    scientific_name: "Rhaponticum",
    german: [
      "Saflor-Bergscharte",
      "Maralwurzel",
      "Maralpflanze",
      "Hirschwurzel",
    ],
    english: ["Maral root", "Rhaponticum"],
    wiki_de: "https://en.wikipedia.org/wiki/Rhaponticum_carthamoides",
    wiki_en: "https://de.wikipedia.org/wiki/Saflor-Bergscharte",
  },
  {
    file_name: "Johannes_B_061",
    scientific_name: "Rhaponticum",
    german: [
      "Saflor-Bergscharte",
      "Maralwurzel",
      "Maralpflanze",
      "Hirschwurzel",
    ],
    english: ["Maral root", "Rhaponticum"],
    wiki_de: "https://en.wikipedia.org/wiki/Rhaponticum_carthamoides",
    wiki_en: "https://de.wikipedia.org/wiki/Saflor-Bergscharte",
  },
  {
    file_name: "Johannes_B_062",
    scientific_name: "Rhaponticum",
    german: [
      "Saflor-Bergscharte",
      "Maralwurzel",
      "Maralpflanze",
      "Hirschwurzel",
    ],
    english: ["Maral root", "Rhaponticum"],
    wiki_de: "https://en.wikipedia.org/wiki/Rhaponticum_carthamoides",
    wiki_en: "https://de.wikipedia.org/wiki/Saflor-Bergscharte",
  },
  {
    file_name: "Johannes_A_031",
    scientific_name: "Geranium",
    german: ["Storchschnäbel", "Geranien"],
    english: ["geraniums", "cranesbills"],
    wiki_de: "https://de.wikipedia.org/wiki/Storchschn%C3%A4bel",
    wiki_en: "https://en.wikipedia.org/wiki/Geranium",
  },
  {
    file_name: "Johannes_A_061",
    scientific_name: "Geranium",
    german: ["Storchschnäbel", "Geranien"],
    english: ["geraniums", "cranesbills"],
    wiki_de: "https://de.wikipedia.org/wiki/Storchschn%C3%A4bel",
    wiki_en: "https://en.wikipedia.org/wiki/Geranium",
  },
  {
    file_name: "Johannes_B_062",
    scientific_name: "Geranium",
    german: ["Storchschnäbel", "Geranien"],
    english: ["geraniums", "cranesbills"],
    wiki_de: "https://de.wikipedia.org/wiki/Storchschn%C3%A4bel",
    wiki_en: "https://en.wikipedia.org/wiki/Geranium",
  },
  {
    file_name: "Johannes_B_065",
    scientific_name: "Geranium",
    german: ["Storchschnäbel", "Geranien"],
    english: ["geraniums", "cranesbills"],
    wiki_de: "https://de.wikipedia.org/wiki/Storchschn%C3%A4bel",
    wiki_en: "https://en.wikipedia.org/wiki/Geranium",
  },
  {
    file_name: "Johannes_B_067",
    scientific_name: "Rheum rhabarbarum",
    german: [
      "Rhabarber",
      "Gemeine Rhabarber",
      "genauer Gewöhnlicher Rhabarber",
      "Gemüse-Rhabarber",
      "Krauser Rhabarber",
    ],
    english: ["Rhubarb"],
    wiki_de: "https://de.wikipedia.org/wiki/Gemeiner_Rhabarber",
    wiki_en: "https://en.wikipedia.org/wiki/Rhubarb",
  },
  {
    file_name: "Johannes_B_068",
    scientific_name: "Rheum rhabarbarum",
    german: [
      "Rhabarber",
      "Gemeine Rhabarber",
      "genauer Gewöhnlicher Rhabarber",
      "Gemüse-Rhabarber",
      "Krauser Rhabarber",
    ],
    english: ["Rhubarb"],
    wiki_de: "https://de.wikipedia.org/wiki/Gemeiner_Rhabarber",
    wiki_en: "https://en.wikipedia.org/wiki/Rhubarb",
  },
  {
    file_name: "Johannes_B_069",
    scientific_name: "Colocasia",
    german: ["Colocasia", "Zehrwurz"],
    english: ["Taro", "elephant-ear", "cocoyam"],
    wiki_de: "https://de.wikipedia.org/wiki/Colocasia_(Pflanzengattung)",
    wiki_en: "https://en.wikipedia.org/wiki/Colocasia",
  },
  {
    file_name: "Johannes_B_081",
    scientific_name: "Musa",
    german: ["Bananen"],
    english: ["Banana"],
    wiki_de: "https://de.wikipedia.org/wiki/Bananen",
    wiki_en: "https://en.wikipedia.org/wiki/Musa_(genus)",
  },
  {
    file_name: "Johannes_B_082",
    scientific_name: "Musa",
    german: ["Bananen"],
    english: ["Banana"],
    wiki_de: "https://de.wikipedia.org/wiki/Bananen",
    wiki_en: "https://en.wikipedia.org/wiki/Musa_(genus)",
  },
  {
    file_name: "Johannes_B_083",
    scientific_name: "Cassia fistula",
    german: [
      "Röhren-Kassie",
      "Purgier-Kassie",
      "Fisett-Kassie",
      "Indischer Goldregen",
    ],
    english: [
      "golden shower",
      "purging cassia",
      "Indian laburnum",
      "pudding-pipe tree",
    ],
    wiki_de: "https://de.wikipedia.org/wiki/R%C3%B6hren-Kassie",
    wiki_en: "https://en.wikipedia.org/wiki/Cassia_fistula",
  },
  {
    file_name: "Johannes_B_088",
    scientific_name: "Myristica fragrans",
    german: ["Muskatnussbaum"],
    english: ["nutmeg", "mace"],
    wiki_de: "https://de.wikipedia.org/wiki/Muskatnussbaum",
    wiki_en: "https://en.wikipedia.org/wiki/Myristica_fragrans",
  },
  {
    file_name: "Johannes_B_096",
    scientific_name: "Valeriana officinalis",
    german: ["Echter Baldrian", "Großer Baldrian", "Baldrian"],
    english: ["Valerian"],
    wiki_de: "https://de.wikipedia.org/wiki/Echter_Baldrian",
    wiki_en: "https://en.wikipedia.org/wiki/Valerian_(herb)",
  },
  {
    file_name: "Johannes_B_098",
    scientific_name: "Gladiolus",
    german: ["Gladiolen", "Schwertblume"],
    english: ["gladioli", "sword lily"],
    wiki_de: "https://de.wikipedia.org/wiki/Gladiolen",
    wiki_en: "https://en.wikipedia.org/wiki/Gladiolus",
  },
  {
    file_name: "Johannes_B_105",
    scientific_name: "Primula veris",
    german: ["Echte Schlüsselblume", "Schlüsselblume"],
    english: ["cowslip", "common cowslip", "cowslip primrose"],
    wiki_de: "https://de.wikipedia.org/wiki/Echte_Schl%C3%BCsselblume",
    wiki_en: "https://en.wikipedia.org/wiki/Primula_veris",
  },
  {
    file_name: "Johannes_B_109",
    scientific_name: "Crocus",
    german: ["Krokusse"],
    english: ["Crocus", "croci"],
    wiki_de: "https://de.wikipedia.org/wiki/Krokusse",
    wiki_en: "https://en.wikipedia.org/wiki/Crocus",
  },
  {
    file_name: "Johannes_A_067",
    scientific_name: "Iris",
    german: ["Schwertlilien", "Iris"],
    english: ["iris"],
    wiki_de: "https://de.wikipedia.org/wiki/Schwertlilien",
    wiki_en: "https://en.wikipedia.org/wiki/Iris_(plant)",
  },
  {
    file_name: "Johannes_B_113",
    scientific_name: "Iris",
    german: ["Schwertlilien", "Iris"],
    english: ["iris"],
    wiki_de: "https://de.wikipedia.org/wiki/Schwertlilien",
    wiki_en: "https://en.wikipedia.org/wiki/Iris_(plant)",
  },
  {
    file_name: "Johannes_B_115",
    scientific_name: "Amaranthus",
    german: ["Amarant", "Fuchsschwanz"],
    english: ["amaranths", "pigweeds"],
    wiki_de: "https://de.wikipedia.org/wiki/Amarant_(Pflanzengattung)",
    wiki_en: "https://en.wikipedia.org/wiki/Amaranth",
  },
];
